name: CI

on: [push]

jobs:
  cancel_previous_run:
    runs-on: ubuntu-latest
    steps:
      - name: Cancel Previous Runs
        uses: styfle/cancel-workflow-action@0.4.0
        with:
          access_token: ${{ github.token }}

  build:
    runs-on: ubuntu-latest
    needs: cancel_previous_run
    steps:
    - uses: actions/checkout@v1
    - name: Setup OCaml
      uses: ocaml/setup-ocaml@v2
    - name: Update packages and install locally
      run: opam install -y .
    - name: Remove package
      run: opam remove -y liquidsoap-daemon
